### ISSUE TITLE
Bug when chrome.storage is full

### ISSUE THREAD

**Issue by badrelmers** [sogryzkov/unreadtab#10]
Hi, the max local chrome storage is 5mb, once this limit is reached your extension can no longer save to it so your  code here is never run and gave error

```javascript
                    object[varName] = 'Updated';
                    chrome.storage.local.set(object);
```

so the tab status is never updated to "Updated",  so the prefix will always be prepended even when only a refresh had happened  which is not what  you want and it is bad in fact because we want the prefix to be prepended only when the tab is opened for the first time not when is loaded from an unloaded state or refreshed...

i think you have to delete the storage entry once the tab is closed so the storage will never get full; or use `chrome.tabs.onCreated.addListener` which will fire only when the tab is first time opened then wait until the tab is loaded to append the prefix (i m still investigating this solution so i don t know if it will work as wanted but seems to be a good route and does not need the use of the storage)

NB: you cannot see the chrome local storage in devtool, you have to use an extension for this , see https://chrome.google.com/webstore/detail/ocfjjjjhkpapocigimmppepjgfdecjkb
once installed open the options page of your extension, open devtool, and see the new tab called Storage Explorer, there you can see/add/remove as you like to the local storage to test the bug i describe here.

thank you for cleaning the old extension, i got a lot of ideas from your extension. good luck

**Comment by badrelmers** [comment]
the solution i described above works very well, here is how i did it:
replace the code that start with:
```javascript
  chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {...
```

replace it with:
```javascript
  chrome.tabs.onCreated.addListener((tab) => {
    chrome.tabs.onUpdated.addListener(
      function tabWasLoadeddd(tabId,changeInfo,thisTab){
        if (thisTab.id == tab.id && thisTab.status && thisTab.status === "complete") {
          chrome.tabs.onUpdated.removeListener(tabWasLoadeddd);
          if (
            !thisTab.active
            && thisTab.url
            && thisTab.url.startsWith('http')
            && !(thisTab.title || '').startsWith(prefix)
          ) {
            const newTitle = prefix + thisTab.title;
            setTabTitle(thisTab.id, newTitle);
          }
        }
      }
    )
  });
```

as you see there is no need to use the storage at all, the prefix is added only when the tab is created for the first time and will never be added when the tab is refreshed or loaded from an unloaded state. thanks to God. 

one more thing, there is not need for this permissions in your manifest: "activeTab","background",
good luck.

**Comment by badrelmers** [comment]
the solution i described above works very well, here is how i did it:
replace the code that start with:
```javascript
  chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {...
```

replace it with:
```javascript
  chrome.tabs.onCreated.addListener((tab) => {
    chrome.tabs.onUpdated.addListener(
      function tabWasLoadeddd(tabId,changeInfo,thisTab){
        if (thisTab.id == tab.id && thisTab.status && thisTab.status === "complete") {
          chrome.tabs.onUpdated.removeListener(tabWasLoadeddd);
          if (
            !thisTab.active
            && thisTab.url
            && thisTab.url.startsWith('http')
            && !(thisTab.title || '').startsWith(prefix)
          ) {
            const newTitle = prefix + thisTab.title;
            setTabTitle(thisTab.id, newTitle);
          }
        }
      }
    )
  });
```

as you see there is no need to use the storage at all, the prefix is added only when the tab is created for the first time and will never be added when the tab is refreshed or loaded from an unloaded state. thanks to God. 

one more thing, there is not need for this permissions in your manifest: "activeTab","background",
good luck.

**Comment by badrelmers** [comment]
another bug is in `setTabTitle(tabId, title)`, you have to catch the errors when setting the title, catching the errors here is important otherwise if the opened site does not exist (like https://sdfsdfq34234.com) then it seems that chrome does not allow to inject our code to change the page title (which is obvious because there is not html code where we can inject our code) and this error is printed: `Frame with ID 0 is showing error page`. and the extension stops working and needs to be reloaded to work again. this small change using `.catch()` solve it:
```javascript
  function setTabTitle(tabId, title) {
    chrome.scripting.executeScript({
      target: { tabId: tabId, allFrames: true },
      func: setDocumentTitle,
      args: [title]
    }).catch(err => console.log("we cannot set the title: " + err));
    // or simply
    // }).catch();
  }
```

**Comment by stanislawru** [comment]
@badrelmers, thank you very much for your attention to our Chrome extension and for your participation! 🙏

> …The max local Chrome storage is 5 Mb…

I have been surpised that it is so small! 😮 However, I have never reached the limit. 🤔

> …You have to delete the storage entry once the tab is closed…

I have done so in the latest version of https://github.com/stanislawru/unread-tab/blob/master/scripts/service_worker.js – added `chrome.tabs.onRemoved.addListener`.

> …There is no need to use the storage at all…

Unfortunately, there is the need to use it – see the description of the version 1.7.0 of the extension.

> …You have to catch the errors when setting the title…

I have done so in the latest version of https://github.com/stanislawru/unread-tab/blob/master/scripts/service_worker.js

Please review my latest changes and approve them here, in a comment, so I could close the issue and release the next version 1.7.5 of the extension.

**Comment by badrelmers** [comment]
> added chrome.tabs.onRemoved.addListener

good, but you added `localStorage.removeItem(varName);`, this is a different storage,  you are saving to `chrome.storage.local` and removing from `localStorage` !

and localStorage is not recomended for extensions:
_While extensions can use the [Storage](https://developer.mozilla.org/docs/Web/API/Storage) interface (accessible from window.localStorage) in some contexts (popup and other HTML pages), we don't recommend it for the following reasons:
	**• Extension service workers can't use the Web Storage API.**
	• Content scripts share storage with the host page.
	• Data saved using the Web Storage API is lost when the user clears their browsing history._
https://developer.chrome.com/docs/extensions/reference/api/storage

___________________________________________________________________
there is another bug in :
```javascript
		chrome.tabs.onActivated.addListener((activeInfo) => {
			chrome.tabs.get(activeInfo.tabId, function (tab) {
				const tabTitle = tab.title || '';
```

catching errors is important here otherwise i get this error sometimes: `Error handling response: TypeError: Cannot read properties of undefined (reading 'title')` then the extension stop working...
and this error: `Unchecked runtime.lastError: No tab with id: 1970363315.`

this error happens when you close a lot of tabs quickly, for example open 10 tabs, now close them one by one very quickly in less than 1s. 

so we have to check if there's an error before accessing the tab object:
```javascript
  chrome.tabs.onActivated.addListener((activeInfo) => {
    chrome.tabs.get(activeInfo.tabId, function (tab) {
      if (chrome.runtime.lastError) {
        console.log(chrome.runtime.lastError.message);
        return; // Exit the callback if there's an error
      }

      const tabTitle = tab.title || '';
```

**Comment by stanislawru** [comment]
@badrelmers wrote:

> you added localStorage.removeItem(varName) – this is a different storage, you are saving to chrome.storage.local and removing from localStorage!

Silly me! 🤦 Thank you for being attentive, I have just fixed it in https://github.com/stanislawru/unread-tab/commit/efb3334a8465c82a57336fa9070bf567a754b946

> There is another bug in chrome.tabs.onActivated… We have to check if there's an error before accessing the tab object…

Thanks for making the code more reliable, I have just fixed it in https://github.com/stanislawru/unread-tab/commit/efb3334a8465c82a57336fa9070bf567a754b946

Please review my latest changes and approve them here, in a comment, so I could close the issue and release the next version 1.7.5 of the extension.

**Comment by badrelmers** [comment]
perfect, thank you.

**Comment by stanislawru** [comment]
@badrelmers, the new release is out and dedicated to you: https://github.com/stanislawru/unread-tab/releases/tag/1.7.5 🙇

**Comment by stanislawru** [comment]
While trying to release it to the Chrome Web Store, I have found out that Google now requires 2FA for this: https://chromeunboxed.com/chrome-extensions-2fa-requirement

**Comment by badrelmers** [comment]
> @badrelmers, the new release is out and dedicated to you: https://github.com/stanislawru/unread-tab/releases/tag/1.7.5 🙇

thank you ❤️ 

> Google now requires 2FA

i hate 2FA lol

**Comment by stanislawru** [comment]
The new version 1.7.5 has been published: https://chrome.google.com/webstore/detail/aabpiidneeojeichdhncnjmdopgglakk

> I hate 2FA…

Nobody likes it (GitHub requires it as well) but it is the price we have to pay in our unsafe world… 😞
