### ISSUE TITLE
Unread marks aren't removed from non-HTML documents

### ISSUE THREAD

**Issue by stanislawru** [sogryzkov/unreadtab#7]
…for example, from https://stanislaw.ru/sitemap.asp

@anton-marchenko, I think this is connected with the issue #5 and thus can be fixed by changing the storage of unread marks from a document (as it can be a non-HTML one) to the extension's one.

**Comment by anton-marchenko** [comment]
This is another example [ads.txt](https://stanislaw.ru/ads.txt)

**Comment by stanislawru** [comment]
The pull request https://github.com/stanislawru/unread-tab/pull/8 closes this issue.
